---
- hosts: all
  sudo: True
  vars:
    repos_dir: "./alminium"
    branch: ubuntu-12.04
  tasks:
    # Run the equivalent of "apt-get update" as a separate step
    - apt: update_cache=yes

    # Install the package "foo"
    - apt: name=git state=present
 
    # テスト
    #  version="{{ branch }}" accept_hostkey="yes"
    
    - git: repo=https://github.com/bols-blue/alminium.git
           dest={{ repos_dir }} version={{ branch }} 


