---
- hosts: all
  sudo: True
  vars:
    repos_dir: "./alminium"
    branch: ubuntu-12.04
  tasks:
    # Run the equivalent of "apt-get update" as a separate step
    - name: "apt のアップデート"
      apt: update_cache=yes

    # Install the package "foo"
    - name: "Gitのインストール"
      apt: name=git state=present
 
    # テスト
    - name: "alminiumのチェックアウト"
      git: repo=https://github.com/bols-blue/alminium.git
           dest={{ repos_dir }} version={{ branch }} 
    #- command: bash ./smelt
    #  args:
    #     chdir: "{{ repos_dir }}"

